"""Словарь известных композитных моделей (где имя содержит _).

Используется в декомпозере чтобы `tiggo_4_pro_2022` НЕ разбивалось на
model=tiggo, а оставалось model=tiggo_4_pro.
"""

KNOWN_MODELS: dict[str, list[str]] = {
    # Chinese composite
    "chery": [
        "tiggo_2", "tiggo_2_pro", "tiggo_3", "tiggo_3x", "tiggo_4", "tiggo_4_pro",
        "tiggo_5", "tiggo_5x", "tiggo_7", "tiggo_7_pro", "tiggo_7_pro_max", "tiggo_8",
        "tiggo_8_pro", "tiggo_8_pro_max", "tiggo_8_plus", "tiggo_9", "arrizo_3",
        "arrizo_5", "arrizo_6", "arrizo_7", "arrizo_8", "qq", "qq3", "qq6",
        "amulet", "bonus", "fora", "omoda",
    ],
    "haval": [
        "h2", "h3", "h5", "h6", "h7", "h8", "h9",
        "f7", "f7x",
        "jolion", "dargo", "big_dog", "bigdog", "m6",
    ],
    "geely": [
        "atlas", "atlas_pro", "coolray", "monjaro", "tugella", "okavango",
        "binray", "emgrand", "emgrand_ev", "emgrand_x7",
    ],
    "byd": [
        "tang", "tang_dm", "tang_ev", "tang_dm_ev", "tang_dm_i",
        "han", "han_dm", "han_ev", "han_dm_i",
        "song", "song_plus", "song_pro", "song_max", "song_ev",
        "qin", "qin_plus", "qin_pro", "qin_ev",
        "yuan", "yuan_plus", "yuan_pro", "yuan_ev",
        "dolphin", "seal", "sealion", "f0", "f3", "f6", "s6", "e6",
    ],
    "changan": [
        "cs15", "cs_15", "cs35", "cs_35", "cs35_plus", "cs_35_plus",
        "cs55", "cs_55", "cs55_plus", "cs_55_plus",
        "cs75", "cs_75", "cs75_plus", "cs_75_plus",
        "cs85", "cs_85", "cs95", "cs_95",
        "uni_t", "uni_k", "uni_v", "uni_s",
        "eado", "raeton", "alsvin",
    ],
    "jetour": [
        "x70", "x70_plus", "x70_m", "x90", "x90_plus",
        "dashing", "t1", "t2",
    ],
    "exeed": [
        "txl", "vx", "lx", "rx", "tx",
    ],
    "tank": ["300", "400", "500", "700"],
    "voyah": ["free", "dream", "courage", "passion"],
    "zeekr": ["001", "007", "009", "x", "8x"],
    "li": ["l7", "l8", "l9", "mega", "one"],
    "li_auto": ["l7", "l8", "l9", "mega", "one"],
    "faw_bestune": ["t77", "t99", "t33", "t55", "t3", "b30", "b70"],
    "hongqi": ["h5", "h7", "h9", "hs3", "hs5", "hs7", "hs9", "e_hs9", "ls7", "qm5", "eh7"],
    "lifan": ["x50", "x60", "x70", "x80", "solano", "smily", "breez", "celliya"],
    "baic": ["bj40", "u5", "u5_plus", "x3", "x7", "eu5"],
    "belgee": ["x50", "x50_plus", "x70", "s50"],
    "livan": ["solano", "x3_pro", "x5", "x7"],
    "kaiyi": ["e5", "x3", "x3_pro", "x7"],
    "forthing": ["t5", "t5l", "yaoguang", "friday", "u_tour"],
    "jac": ["j7", "s3", "s7", "t6", "t8", "iev"],
    "jaecoo": ["j7", "j8"],
    "gac": ["aion_lx", "aion_s", "aion_v", "aion_y", "gs4", "gs5", "gs8", "ga8", "ga4"],
    "mg": ["zs", "hs", "rx5", "rx8", "gs", "6", "5", "3"],
    "xpeng": ["p5", "p7", "g3", "g6", "g9", "x9"],
    "nio": ["es6", "es7", "es8", "ec6", "ec7", "et5", "et7", "et9"],
    # Western — многие с дефисом/числом становятся одним токеном после normalize
    "mazda": ["cx_3", "cx_5", "cx_7", "cx_9", "cx_30", "mx_5", "rx_8", "bt_50",
              "cx3", "cx5", "cx7", "cx9", "cx30", "mx5", "rx8", "bt50",
              "mazda2", "mazda3", "mazda5", "mazda6",
              "2", "3", "5", "6", "premacy", "demio", "tribute"],
    "opel": ["astra", "corsa", "vectra", "vectra_c", "vectra_b", "zafira",
             "meriva", "meriva_b", "combo", "combo_life", "insignia", "insignia_b",
             "mokka", "grandland", "crossland", "frontera", "omega", "signum", "agila",
             "vivaro", "movano", "antara"],
    "peugeot": ["106", "107", "108", "206", "207", "208", "301", "306", "307", "308",
                "3008", "4008", "406", "407", "408", "508", "5008", "806", "807",
                "1007", "rcz", "partner", "boxer", "expert"],
    "renault": ["clio", "megane", "laguna", "scenic", "duster", "kaptur", "kangoo",
                "logan", "sandero", "captur", "fluence", "koleos", "master", "modus",
                "espace", "traffic", "symbol", "talisman", "twingo", "latitude", "arkana"],
    "ford": ["focus", "fiesta", "mondeo", "kuga", "escape", "explorer", "edge",
             "ecosport", "s_max", "galaxy", "fusion", "mustang", "ranger", "transit",
             "territory", "taurus", "f_150", "expedition"],
    "chevrolet": ["aveo", "cruze", "captiva", "cobalt", "spark", "lacetti", "niva",
                  "lanos", "camaro", "corvette", "equinox", "traverse", "tahoe",
                  "impala", "malibu", "silverado", "suburban", "trax", "trailblazer",
                  "blazer", "orlando", "epica", "rezzo", "evanda", "aveo_t250", "aveo_t300",
                  "cruze_j300", "cruze_j400"],
    "cadillac": ["escalade", "ats", "cts", "xts", "xt4", "xt5", "xt6", "srx", "sts"],
    "dodge": ["caravan", "challenger", "charger", "ram", "journey", "durango", "avenger",
              "viper", "neon", "stealth"],
    "jeep": ["grand_cherokee", "cherokee", "wrangler", "compass", "patriot", "renegade",
             "gladiator", "commander"],
    "jaguar": ["xe", "xf", "xj", "xk", "f_type", "e_type", "f_pace", "e_pace", "i_pace"],
    "land_rover": ["range_rover", "range_rover_sport", "range_rover_evoque",
                   "range_rover_velar", "discovery", "discovery_sport", "defender", "freelander"],
    "hyundai": ["accent", "solaris", "elantra", "sonata", "tucson", "santa_fe",
                "creta", "ix35", "ix55", "h1", "h200", "h350", "getz", "equus",
                "veloster", "palisade", "staria", "starex", "i30", "i40"],
    "kia": ["rio", "cerato", "optima", "k5", "k7", "k9", "forte", "sportage", "sorento",
            "mohave", "soul", "carnival", "stinger", "stonic", "seltos", "picanto",
            "ceed", "niro", "ev6", "ev9", "telluride", "carens", "venga", "morning"],
    "mitsubishi": ["lancer", "outlander", "asx", "rvr", "pajero", "pajero_sport",
                   "l200", "galant", "colt", "mirage", "eclipse", "space_wagon",
                   "3000gt", "fuso", "airtrek"],
    "subaru": ["impreza", "legacy", "outback", "forester", "xv", "crosstrek",
               "brz", "wrx", "tribeca", "baja", "ascent", "legacy_outback"],
    "infiniti": ["q30", "q50", "q60", "q70", "qx30", "qx50", "qx55", "qx60",
                 "qx70", "qx80", "fx", "m", "ex", "jx", "g"],
    "lexus": ["is", "es", "gs", "ls", "ct", "hs", "rc", "lc", "nx", "rx", "gx", "lx", "ux"],
    "suzuki": ["swift", "vitara", "grand_vitara", "sx4", "jimny", "celerio",
               "baleno", "dzire", "ciaz", "alto", "wagon_r", "escudo"],
    "volkswagen": ["polo", "golf", "jetta", "passat", "tiguan", "touareg", "touran",
                   "sharan", "amarok", "atlas", "arteon", "teramont", "caddy",
                   "transporter", "multivan", "caravelle", "beetle", "scirocco",
                   "phaeton", "id_3", "id_4", "id_6"],
    "skoda": ["fabia", "octavia", "rapid", "superb", "yeti", "kodiaq", "karoq",
              "kamiq", "scala", "roomster"],
    "audi": ["a1", "a3", "a4", "a5", "a6", "a7", "a8", "q2", "q3", "q4", "q5",
             "q6", "q7", "q8", "tt", "r8"],
    "bmw": ["1_series", "2_series", "3_series", "4_series", "5_series", "6_series",
            "7_series", "8_series", "x1", "x2", "x3", "x4", "x5", "x6", "x7",
            "z3", "z4", "i3", "i4", "i5", "i7", "i8", "ix"],
    "mercedes": ["a_class", "b_class", "c_class", "e_class", "s_class",
                 "cla", "cls", "gla", "glb", "glc", "gle", "glk", "gls",
                 "g_class", "m_class", "v_class", "vito", "sprinter", "viano"],
    "mercedes_benz": ["a_class", "b_class", "c_class", "e_class", "s_class",
                      "cla", "cls", "gla", "glb", "glc", "gle", "glk", "gls",
                      "g_class", "m_class", "v_class", "vito", "sprinter", "viano"],
    "porsche": ["911", "718", "panamera", "macan", "cayenne", "taycan"],
    "lada": ["granta", "kalina", "largus", "priora", "samara", "vesta", "xray",
             "niva", "niva_travel", "2104", "2105", "2106", "2107", "2108", "2109",
             "2110", "2111", "2112", "2113", "2114", "2115"],
    "uaz": ["patriot", "hunter", "pickup", "profi", "3151", "3163", "3909", "2206", "452"],
    "gaz": ["gazelle", "gazelle_next", "volga", "siber", "sobol"],
    "datsun": ["on_do", "mi_do"],
    "nissan": ["almera", "sentra", "sunny", "versa", "latio", "teana", "altima",
               "maxima", "murano", "x_trail", "qashqai", "pathfinder", "navara",
               "terrano", "note", "juke", "gt_r", "leaf", "micra", "march", "tiida",
               "kicks", "patrol", "bluebird"],
    "honda": ["civic", "accord", "cr_v", "pilot", "odyssey", "jazz", "fit", "hr_v",
              "ridgeline", "insight", "legend", "passport", "element", "crosstour",
              "prelude"],
    "toyota": ["camry", "corolla", "rav4", "land_cruiser", "prado", "avensis",
               "highlander", "fortuner", "hilux", "prius", "yaris", "aygo", "auris",
               "verso", "venza", "c_hr", "supra", "86"],
    "seat": ["ibiza", "leon", "toledo", "altea", "arosa", "cordoba", "exeo",
             "ateca", "arona", "tarraco"],
    "fiat": ["panda", "500", "punto", "grande_punto", "bravo", "stilo", "multipla",
             "doblo", "ducato", "tipo", "cinquecento", "seicento", "palio", "uno",
             "siena", "marea", "linea", "albea"],
    "smart": ["fortwo", "forfour", "roadster", "crossblade"],
    "mini": ["cooper", "countryman", "clubman", "paceman", "roadster", "cabrio"],
    "tesla": ["model_s", "model_3", "model_x", "model_y", "cybertruck"],
    "acura": ["mdx", "rdx", "tsx", "tl", "rl", "ilx", "tlx", "nsx", "zdx", "integra"],
    "lincoln": ["navigator", "continental", "mkc", "mkx", "mkz", "nautilus", "aviator", "corsair"],
    "chrysler": ["300", "300c", "pacifica", "town_country", "voyager", "sebring",
                 "cirrus", "neon", "crossfire"],
    "volvo": ["s40", "s60", "s70", "s80", "s90", "v40", "v50", "v60", "v70", "v90",
              "xc40", "xc60", "xc70", "xc90", "c30", "c40", "c70"],
    "saab": ["900", "9_3", "9_5", "9_7x", "93", "95"],
    "ssangyong": ["actyon", "korando", "kyron", "rexton", "rodius", "musso",
                  "tivoli", "stavic", "torres"],
    "isuzu": ["d_max", "mu_x", "trooper", "rodeo", "ascender"],
    "bmw_motorrad": [],  # мотоциклы, игнор
}


# Suffix'ы которые нельзя считать именем поколения (если это гибридная/языковая вариация)
VARIANT_SUFFIXES = {
    "_ru", "_en", "_eng", "_de", "_fr", "_es", "_it", "_zh", "_jp",
    "_lhd", "_rhd", "_fwd", "_awd", "_ocr", "_reocr", "_stub",
    "_v1", "_v2", "_v3",
}
